
#- name: Create Hosted Zone 
# shell: aws route53 create-hosted-zone --name demo2.csye6225-fall2018-rajanjerin.me --caller-reference csye6225-fall2018-rajanjerin.me 

- name: Get Parent ID
  shell: export parentZoneId=`aws route53 list-hosted-zones | jq '.HostedZones[] | select(.Name=="csye6225-fall2018-rajanjerin.me.") | .Id'| cut -d/ -f3|cut -d\" -f1`
  shell: "echo $parentZoneId"

- name: Get Subdomain ID
  shell: export subdomainZoneId=`aws route53 list-hosted-zones | jq '.HostedZones[] | select(.Name=="demo2.csye6225-fall2018-rajanjerin.me") | .Id'| cut -d/ -f3|cut -d\" -f1`

- name: Export NS
  shell: export NS=`aws route53 list-resource-record-sets --hosted-zone-id $subdomainZoneId  | jq .ResourceRecordSets[0].ResourceRecords`

- name: Replace RecordName and Resource Set Name Server
  shell: cat subdomain_test.json | jq '.Changes[0].ResourceRecordSet.ResourceRecords[0]=env.NS' > /etc/ansible/csye7374-spring2019-template-master/ansible/roles/kops/setup/tasks/subdomain.json
  shell: sudo sed -i 's/\\n//g' /etc/ansible/csye7374-spring2019-template-master/ansible/roles/kops/setup/tasks/subdomain.json
  shell: sudo sed -i 's/\\//g' /etc/ansible/csye7374-spring2019-template-master/ansible/roles/kops/setup/tasks/subdomain.json
  register: cat /etc/ansible/csye7374-spring2019-template-master/ansible/roles/kops/setup/tasks/subdomain.json  
  debug: msg={{cat /etc/ansible/csye7374-spring2019-template-master/ansible/roles/kops/setup/tasks/subdomain.json}}
  #- name: Mapping Subdomain NS record set with the Parent Domain
  #shell: aws route53 change-resource-record-sets --hosted-zone-id $parentZoneId --change-batch file:///etc/ansible/csye7374-spring2019-template-master/ansible/roles/kops/setup/tasks/subdomain.json
